# 开发环境配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.163.com
    username: Javastudy1@163.com
    password: YUVRVNKZTTIUMADI
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    addresses: 121.43.124.159
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  data:
    redis:
      database: 0
      host: 121.43.124.159
      username: default
      password: redis_B56zTM
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: FmNzcwG35GdrT62S
    url: jdbc:mysql://121.43.124.159:3306/test
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'
    minio:
      endpoint: 'http://121.43.124.159:9000'
      username: 'minio_HsDNRR'
      password: 'minio_mDQrR4'
  weather:
    key: "ff2c20090d1d43d89d03aa21d02f224c"
