#生产环境配置
server:
  port: 8081
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.163.com
    username: Javastudy1@163.com
    password: YUVRVNKZTTIUMADI
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    addresses: 127.0.0.1
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  data:
    redis:
      database: 0
      host: localhost
      username: default
      password: redis_ABSnB5
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: forum
    password: A2fZPsSdAjjhP4cB
    url: jdbc:mysql://localhost:3306/forum
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'
    minio:
      endpoint: 'http://localhost:9000'
      username: 'minio_eR8t6x'
      password: 'minio_8zJaBc'
  weather:
    key: "ff2c20090d1d43d89d03aa21d02f224c"
    host: "mx2yvv8g69.re.qweatherapi.com"